#include "tzstruct.h"
#include <time.h>
#include <stdio.h>

// uses the simple timezone data to determine if the clock should
// adjust for Daylight Savings Time.
// The actual adjustments are generated by another programme incuded
// in the repo (tzadj).

int tz_shouldaddanhour(time_t epoch) {
	int i;
	i = 0;
	do {
		//printf("%ld: %ld %ld\n", (long int)epoch, (long int)timezonechanges[i].startsat, (long int)timezonechanges[i].endsat);
		if (((long int)epoch > (long int)timezonechanges[i].startsat) &&
				((long int)epoch < (long int)timezonechanges[i].endsat)) {
			//printf("Y\n");
			return 1;
		}
		//fprintf(stdout, "%ld: %ld %ld\n", epoch, timezonechanges[i].startsat, timezonechanges[i].endsat);
		i ++;
	} while (timezonechanges[i].startsat != 0 && epoch > timezonechanges[i].startsat);
	//printf("N\n");
	return 0;
}

